[package]
name = "Hex_to_WIF"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.30.0"
secp256k1 = {version = "0.27.0", features = ["rand"]}