[package]
name = "Hex_to_WIF"
version = "0.3.0"
edition = "2021"

build = "build.rs"

[dependencies]
bitcoin = "0.30.0"
secp256k1 = {version = "0.27.0", features = ["rand"]}



[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"